apiVersion: v1
kind: Namespace
metadata:
  name: fga-backend
  labels:
    name: fga-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fga-backend
  name: deployment-reader
rules:
- apiGroups: ["apps/v1"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-deployments
  namespace: fga-backend
subjects:
- kind: Group
  name: fga-backend
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io